// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ismsaumgtplqbwsfulaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzbXNhdW1ndHBscWJ3c2Z1bGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTM0MjUsImV4cCI6MjA2NjUyOTQyNX0.nlpzLlOXckl4HTsxiPnadSclDKW_TegJRCONEwjF9js";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);